pipeline {
    agent none  // No default agent, each stage uses its own Docker agent or Jenkins agent
    
    environment {
        // JIRA_PROJECT_KEY = 'PROJ'
        // JIRA_PROJECT_KEY = 'MP'
        JIRA_PROJECT_KEY = 'CCE'
        // JIRA_SITE = 'ml-projects'
        JIRA_SITE = 'ci-cd-project'
    }
    
    stages {
        // stage('Get From Github') {
        //     agent {
        //         docker {
        //             image 'alpine/git:latest'
        //             args '--entrypoint='
        //         }
        //     }
        //     steps {
        //         script {
        //             checkout scm
        //             sh 'echo "Fetching code from GitHub repository"'
        //             sh 'git log -1 --pretty=format:"%h - %an, %ar : %s"'
        //         }
        //     }
        // }

        stage('Create Issue on JIRA') {
            agent any
            steps {
                script {
                    echo 'Creating issue on JIRA'
                    jiraNewIssue site: env.JIRA_SITE, issue: [
                        fields: [
                            project: [key: env.JIRA_PROJECT_KEY],
                            summary: 'New issue from Jenkins',
                            description: '''This is a new issue from Jenkins
                            Build Number: ${env.BUILD_NUMBER}
                            Branch: ${env.BRANCH_NAME}
                            Duration: ${env.currentBuild.durationString}
                            Failed Stage: ${env.STAGE_NAME}
                            Build URL: ${env.BUILD_URL}
                            ''',
                            issuetype: [name: 'Bug']
                        ]
                    ]
                }
            }
        }
        
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
    }
}
