pipeline {
    agent none  // No default agent, each stage uses its own Docker agent or Jenkins agent
    
    environment {
        // JIRA_PROJECT_KEY = 'PROJ'
        JIRA_PROJECT_KEY = 'MP'
    }
    
    stages {
        stage('Get From Github') {
            agent {
                docker {
                    image 'alpine/git:latest'
                    args '--entrypoint='
                }
            }
            steps {
                script {
                    checkout scm
                    sh 'echo "Fetching code from GitHub repository"'
                    sh 'git log -1 --pretty=format:"%h - %an, %ar : %s"'
                }
            }
        }

        stage('Create Issue on JIRA') {
            agent any
            steps {
                script {
                    echo 'Creating issue on JIRA'
                    jiraNewIssue site: 'MyJiraSite', issue: [
                        fields: [
                            project: [key: env.JIRA_PROJECT_KEY],
                            summary: 'New issue from Jenkins',
                            issuetype: [name: 'Bug']
                        ]
                    ]
                }
            }
        }
        
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
    }
}
